version: "3.3"
services:
  db:
    image: mysql:5.7
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: eba
    volumes:
      - my-db:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 10M
    ports:
      - 8080:80
volumes:
  my-db:
