USE toon;
CREATE TABLE users (
    id integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstname varchar(15) NOT NULL,
    lastname varchar(15) NOT NULL,
    email varchar(255)
); 


    INSERT INTO `users` (`id`,`firstname`,`lastname`,`email`) VALUES (1,"Ethan","Barber","purus.ac.tellus@elitAliquam.edu"),(2,"Alfonso","Fleming","Proin.eget.odio@ipsum.ca"),(3,"Graiden","Hardin","a.scelerisque@fermentum.net"),(4,"Lana","Lamb","quis.pede.Suspendisse@faucibus.net"),(5,"Cailin","Jackson","Cras.eget@tristique.edu"),(6,"TaShya","Walter","mi@amet.com"),(7,"Uma","Blackburn","aliquam@tellusAeneanegestas.edu"),(8,"Vance","Christian","euismod.est@malesuadafringillaest.ca"),(9,"Yolanda","Stafford","convallis.ante.lectus@fermentumconvallis.com"),(10,"Flynn","Winters","molestie@aultricies.com");
    INSERT INTO `users` (`id`,`firstname`,`lastname`,`email`) VALUES (11,"Dale","Hampton","nibh.dolor.nonummy@elementum.net"),(12,"Phelan","Page","amet.metus.Aliquam@necorci.net"),(13,"Alma","Black","dictum.eleifend@Sednec.net"),(14,"Kirestin","Preston","diam.eu@lacuspedesagittis.co.uk"),(15,"Felicia","Johnson","aliquet.Phasellus@orcilacusvestibulum.net"),(16,"Glenna","Preston","mus.Donec.dignissim@Phasellusnulla.com"),(17,"Rigel","James","Sed.auctor@consectetueradipiscing.ca"),(18,"Sybill","Huff","Maecenas.mi.felis@nonummyipsumnon.com"),(19,"Heather","Marshall","aliquet@musProin.com"),(20,"Ayanna","Bender","tincidunt.pede.ac@ProinmiAliquam.com");
    INSERT INTO `users` (`id`,`firstname`,`lastname`,`email`) VALUES (21,"Jada","Rutledge","erat@bibendum.ca"),(22,"Roanna","Quinn","Nulla.tempor.augue@idblandit.edu"),(23,"Lacota","Hudson","vitae@nequeNullamnisl.co.uk"),(24,"Bree","Carrillo","morbi.tristique.senectus@ullamcorpernislarcu.com"),(25,"Yoko","Ortiz","quis.urna.Nunc@tellusAenean.net"),(26,"Henry","Garza","ipsum@dignissimMaecenasornare.edu"),(27,"Cruz","Weeks","arcu.Vestibulum.ante@Sedeget.org"),(28,"Rylee","Davis","sed@semper.co.uk"),(29,"Myles","Martin","faucibus@sodalesatvelit.edu"),(30,"Dawn","Hewitt","pharetra.ut@erosturpisnon.com");
    INSERT INTO `users` (`id`,`firstname`,`lastname`,`email`) VALUES (31,"Fatima","Rios","luctus.ipsum.leo@lobortis.org"),(32,"Justine","Dejesus","arcu.iaculis.enim@nulla.edu"),(33,"Clio","Suarez","enim.Mauris@dictum.co.uk"),(34,"Ivana","Conley","amet.lorem.semper@commodoipsum.ca"),(35,"Myra","Dejesus","lacinia@dui.org"),(36,"Arden","Forbes","lorem@ligula.com"),(37,"Martin","Gregory","enim@auctorvelit.edu"),(38,"Grady","Durham","Etiam@nascetur.com"),(39,"Sybill","Rodgers","eget.lacus.Mauris@nostra.com"),(40,"Skyler","Harding","nibh.Quisque@Proinsedturpis.net");
    INSERT INTO `users` (`id`,`firstname`,`lastname`,`email`) VALUES (41,"Cara","Case","orci.consectetuer.euismod@et.org"),(42,"Jocelyn","Zamora","Nullam.velit@Vivamus.co.uk"),(43,"Keiko","Miranda","tellus.eu.augue@molestietortornibh.edu"),(44,"Thomas","Curtis","tellus.lorem.eu@dictum.org"),(45,"Ria","Keith","dolor.quam.elementum@pedeultricesa.org"),(46,"Porter","Dejesus","eu.ligula@Nullam.com"),(47,"Taylor","Chen","a.scelerisque.sed@etultricesposuere.ca"),(48,"Shelley","Luna","ornare.libero@pharetrased.ca"),(49,"Axel","Mendoza","fringilla.porttitor.vulputate@tempusmauris.net"),(50,"Xanthus","Farmer","amet.consectetuer.adipiscing@utlacusNulla.co.uk");
